// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joygrdtepsicsduvbazm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveWdyZHRlcHNpY3NkdXZiYXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDQzNzQsImV4cCI6MjA2NzkyMDM3NH0.S1e8DGteRD8U8Fg9wfF7FRlMPpi2sLj1ll-ALn0h3wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});